
[platformio]
default_envs = fc
boards_dir = boards

[env:fc]
platform = ststm32
board = g473rc
framework  = arduino

build_flags =
    -D USBCON
    -D USBD_USE_CDC
    -D USBD_VID=0x0483
    -D USBD_PID=0x5740
    -D HAL_PCD_MODULE_ENABLED
    -D HAL_TIM_MODULE_ENABLED
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D HAL_UART_MODULE_ENABLED
    -O2
    -std=gnu++17
build_unflags = -std=gnu++14

upload_protocol = stlink
debug_tool      = stlink

monitor_speed = 115200

[env:fc_dfu]
extends         = env:fc
upload_protocol = dfu

[env:fc_debug]
extends    = env:fc
build_type = debug
build_flags = ${env:fc.build_flags} -g -Og